### ISSUE TITLE
how does this work

### ISSUE THREAD

**Issue by Makoto40renta** [KuromeSan/FlashPatcher#2]
im really new in this kind of stuff so

**Comment by Makoto40renta** [comment]
oh wait, nvm, i just downloade the source code instead of the thing. sorry

**Comment by KuromeSan** [comment]
Uh how it works? Well normally flash will get the current time as a Unix Epoch (Which is just the number of seconds since Jan 1st 1970) and then check if it's less than 1610409600000 which is January 12 2021. FlashPatcher just does a find and replace on the Flash Executable files for this number- and replaces it with "Infinity". And since every number is less than Infinity. It never gets locked out.

**Comment by Makoto40renta** [comment]
> Uh how it works? Well normally flash will get the current time as a Unix Epoch (Which is just the number of seconds since Jan 1st 1970) and then check if it's less than 1610409600000 which is January 12 2021. FlashPatcher just does a find and replace on the Flash Executable files for this number- and replaces it with "Infinity". And since every number is less than Infinity. It never gets locked out.

the actual question was, "how do i run this?"
like, i downloaded the source code by accident instead of the .exe and i was confused about how do i start this thing?
i already knew what the program does, i was just struggling how to run the source code lol
sorry for the inconvenience

btw the program worked fine, thank you so much
